global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'iot_app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'mongo_db'
    static_configs:
      - targets: ['mongo-exporter:9216']